name: Build-Default
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          version: '14.1'
          shell: sh
          run: |
            uname -a
            echo $SHELL
            pwd
            ls -lah
            whoami
            env | sort
            pkg install -y libXpm
            pkg info
            ./configure --with-xpm-includes=/usr/local/include --with-xpm-library=/usr/local/lib
            make
            make install
