name: Build-Default
on: workflow_dispatch
env:
  DEV: YES

jobs:
  build-default:
    name: build-default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          version: '14.1'
          shell: sh
          memory: 2G
          cpu_count: 2
          run: |
            uname -a
            pwd
            ls -lah
            whoami
            env
            pkg bootstrap -f
            pkg install -y libXpm
            pkg info
            ./configure --with-xpm-includes=/usr/local/include --with-xpm-library=/usr/local/lib
            make
            make install
