name: Build-Default
on: workflow_dispatch
env:
  DEV: YES

jobs:
  build-default:
    name: build-default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: cross-platform-actions/action@v0.25.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '14.1'
          shell: sh
          memory: 2G
          cpu_count: 2
          environment_variables: DEV ASSUME_ALWAYS_YES
          run: |
            uname -a
            pwd
            ls -lah
            whoami
            env
            sudo pkg install -y libXpm
            pkg info
            ./configure --with-xpm-includes=/usr/local/include --with-xpm-library=/usr/local/lib
            make
            sudo mkdir -p /usr/local/man/man1
            sudo make install
